from . import ir_actions_server
from . import res_company
from . import qc_parameter
from . import pdi_parameter
from . import account_move
from . import mrp_production
from . import mrp_unbuild
from . import bulk_barcode_wizard
from . import batch_mo_wizard
from . import product_template
from . import purchase_order
from . import sale_order
from . import sale_order_reject_wizard
from . import stock_move
from . import stock_picking_type
from . import stock_picking
from . import stock_lot
from . import stock_picking_qc_wizard
from . import consolidated_pi_generator
from . import generate_pi_wizard
from . import purchase_bom_wizard
from . import invoice_bike_scan_wizard
from . import global_scan_wizard
from . import delivery_bike_scan_wizard
from . import delivery_change_wizard
from . import combo_price
from . import res_partner
from . import finance_api
from . import warranty
from . import new_bike_model_wizard
